language: c

matrix:
  include:
    - env: NAME="Ubuntu 32bit"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis daald/ubuntu32:xenial tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
          linux32 --32bit i386 ./build.sh &&
          tree"

    - env: NAME="Ubuntu 32bit staging"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis daald/ubuntu32:xenial tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis; linux32 --32bit i386 ./build-staging.sh"

    - env: NAME="Ubuntu 64bit"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
          ./build.sh --enable-win64 &&
          tree"

    - env: NAME="Ubuntu 64bit staging"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis; ./build-staging.sh --enable-win64"

    - env: NAME="OSX 32bit"
      os: osx
      osx_image: xcode9.2
      install:
        - ./install-osx-deps.sh
      script:
        - ./build.sh

    - env: NAME="OSX 32bit staging"
      os: osx
      osx_image: xcode9.2
      install:
        - ./install-osx-deps.sh
      script:
        - ./build-staging.sh

    - env: NAME="OSX 64bit"
      os: osx
      osx_image: xcode9.2
      install:
        - ./install-osx-deps.sh
      script:
        - ./build.sh --enable-win64

    - env: NAME="OSX 64bit staging"
      os: osx
      osx_image: xcode9.2
      install:
        - ./install-osx-deps.sh
      script:
        - ./build-staging.sh --enable-win64
