language: c

matrix:
  include:
    - env: NAME="Ubuntu 64bit"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
          git clone https://github.com/wine-mirror/wine.git &&
          mkdir build-64bit &&
          cd build-64bit &&
          ../wine/configure --enable-win64 &&
          make -j2 &&
          tree"
    - env: NAME="Ubuntu 64bit staging"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
      install:
        - ./install-ubuntu-deps-docker.sh
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
          git clone https://github.com/wine-mirror/wine.git &&
          # TBD: use https://github.com/alesliehughes/alesliehughes-wine-staging.git
          git clone https://github.com/wine-compholio/wine-staging.git &&
          ./wine-staging/patches/patchinstall.sh DESTDIR=wine --all
          mkdir build-64bit &&
          cd build-64bit &&
          ../wine/configure --enable-win64 &&
          make -j2 &&
          tree"
    - env: NAME="OSX 64bit"
      os: osx
      osx_image: xcode9.2
      install:
        - brew install caskroom/cask/xquartz
        - brew install --only-dependencies caskroom/versions/wine-devel
        - brew install gettext
        - brew install libquicktime
        - brew install libgphoto2
        - brew install libgsm
        - brew install gst-plugins-base
        - brew install openal-soft
      script:
        - git clone https://github.com/wine-mirror/wine.git
        - mkdir build-64bit
        - cd build-64bit
        - ../wine/configure --enable-win64
        - make -j2
