#!/bin/sh
docker exec -t ubuntu-18-04 bash -c "apt-get -qq update;
                                     apt-get install -y git;
                                     apt-get install -y gcc;
                                     apt-get install -y tree;
                                     apt-get install -y flex;
                                     apt-get install -y bison;
                                     apt-get install -y libfreetype6-dev;
                                     apt-get install -y libxcursor-dev;
                                     apt-get install -y libxi-dev;
                                     apt-get install -y libxrandr-dev;
                                     apt-get install -y libxinerama-dev;
                                     apt-get install -y libxcomposite-dev;
                                     apt-get install -y mesa-common-dev;
                                     apt-get install -y libosmesa6-dev;
                                     apt-get install -y ocl-icd-opencl-dev;
                                     apt-get install -y libpcap-dev;
                                     apt-get install -y libdbus-1-dev;
                                     apt-get install -y libsane-dev;
                                     apt-get install -y libv4l-dev;
                                     apt-get install -y libgphoto2-dev;
                                     apt-get install -y libgphoto2-port12;
                                     apt-get install -y libpulse-dev;
                                     apt-get install -y libgstreamer-plugins-base1.0-dev;
                                     apt-get install -y libudev-dev;
                                     apt-get install -y libegl1-mesa-dev;
                                     apt-get install -y libgles2-mesa-dev;
                                     apt-get install -y libsdl2-dev;
                                     apt-get install -y libcapi20-dev;
                                     apt-get install -y libcups2-dev;
                                     apt-get install -y libgsm1-dev;
                                     apt-get install -y libmpg123-dev;
                                     apt-get install -y libopenal-dev;
                                     apt-get install -y libncurses5-dev;
                                     apt-get install -y liblcms2-dev;
                                     apt-get install -y libfontconfig1-dev;
                                     apt-get install -y libkrb5-dev;
                                     apt-get install -y libgssapi-krb5-2;
                                     apt-get install -y libtiff5-dev;
                                     apt-get install -y libldap2-dev;
                                     apt-get install -y libxslt1-dev;
                                     apt-get install -y libgnutls-dev;
                                     apt-get install -y libjpeg-dev;
                                     apt-get install -y oss4-dev;
                                     apt-get install -y wget;
				     apt-get install -y unzip;
                                     apt-get install -y pkg-config;
				     apt-get install -y libgnutls28-dev;
				     apt-get install -y libxcb-keysyms1-dev;
				     apt-get install -y libxcb-util0-dev;
				     apt-get install -y libxcb-icccm4-dev;
                                     apt-get install -y libvulkan-dev;
				     wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/spirv-headers/1.3-1/spirv-headers_1.3.orig.tar.gz ;
				     tar -zxvf spirv-headers_1.3.orig.tar.gz;
				     mv spirv-headers-1.3/include/spirv /usr/include;
				     wget https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip;
				     unzip SPIRV-Tools-master-linux-RelWithDebInfo.zip -d spirv-tools/;
				     cp spirv-tools/bin/* /usr/bin;
				     cp -r spirv-tools/include/* /usr/include;
				     cp -r spirv-tools/lib/* /usr/lib;
				     apt-get install -y libgtk-3-dev;
				     apt-get install -y libva-dev"
